services:
  - type: web
    name: xrpl-deepflow
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: "/healthz"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: MIN_XRP
        value: "1000000"
